spring.application.name=UserSecurityService


spring.datasource.url=jdbc:mysql://localhost:3306/springsecurity?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.sql.init.platform=MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


application.security.jwt.secret-key=amantiwari8861@gmail.com_this_is_a_perfect_secret_key
application.security.jwt.expiration=3600000
application.security.jwt.refresh-expiration=86400000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG